vich_uploader:
    db_driver: orm

    mappings:
        uploaded_image:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        uploaded_templates:
            uri_prefix: /uploads/templates
            upload_destination: '%kernel.project_dir%/public/uploads/templates'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
