vich_uploader:
    db_driver: orm

    mappings:
        uploaded_image:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        uploaded_fluid_image:
            uri_prefix: /uploads/images/fluid
            upload_destination: '%kernel.project_dir%/public/uploads/images/fluid'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
